### ISSUE TITLE
カスタムドメインを入れた方がいいと思います。

### ISSUE THREAD

**Issue by The-Infinitys** [nekogakure/nekogakure.github.io#2]
ドメインのいい例としては、
[ddns now](https://f5.si)これとかが良いかと。
何よりもGoogle Adsenseに登録できるらしい

**Comment by nekogakure** [comment]
> ドメインのいい例としては、 [ddns now](https://f5.si)これとかが良いかと。 何よりもGoogle Adsenseに登録できるらしい

いやー、もうnekogakure.f5.siでゲットしてるんだけど設定できない。カスタムドメインのとこにれてもエラー吐きやがる

**Comment by nekogakure** [comment]
あ、出来ました[これ](nekogakure.f5.si)

**Comment by nekogakure** [comment]
nekogakure.f5.siで多分いけるはずです
